In [279]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from sklearn.ensemble import HistGradientBoostingRegressor
import joblib

## load_data

In [280]:
def load_data(folder_path):
    dataframes = []
    for filename in os.listdir(folder_path):
        if filename.endswith('.csv'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            category = os.path.splitext(filename)[0]
            df['Category'] = category
            dataframes.append(df)
    if dataframes:
        merged_data = pd.concat(dataframes, ignore_index=True)
        merged_data['Date'] = pd.to_datetime(merged_data['Date'])
        merged_data.set_index('Date', inplace=True)
    else:
        print("No CSV files found in the specified folder.")
        return pd.DataFrame()

    return merged_data

In [281]:
def load_data2(base_folder_path):
    dataframes = []
    
    for category in os.listdir(base_folder_path):
        category_path = os.path.join(base_folder_path, category)
        
        if os.path.isdir(category_path):
            for filename in os.listdir(category_path):
                if filename.endswith('.csv'):
                    file_path = os.path.join(category_path, filename)
                    df = pd.read_csv(file_path)
                    df['Category'] = category
                    province = os.path.splitext(filename)[0]
                    df['Province'] = province
                    price_columns = df.columns.difference(['Date', 'Category', 'Province'])
                    if not price_columns.empty:
                        df['Price'] = df[price_columns[0]]
                    else:
                        print(f"No price column found in {filename}. Skipping this file.")
                        continue
                    
                    dataframes.append(df)
    
    if dataframes:
        merged_data = pd.concat(dataframes, ignore_index=True)
        merged_data['Date'] = pd.to_datetime(merged_data['Date'])
    else:
        print("No CSV files found in the specified folder.")
        return pd.DataFrame()
    merged_data2 = merged_data.pivot_table(index=['Date', 'Category'], columns='Province', values='Price', aggfunc='first')

    merged_data2.reset_index(inplace=True)
    merged_data2['Category'] = merged_data2['Category'].replace({
    'bawang merah': 'Bawang Merah',
    'bawang putih': 'Bawang Putih Bonggol',
    'cabai merah': 'Cabai Merah Keriting',
    'cabai rawit': 'Cabai Rawit Merah',
    'daging ayam': 'Daging Ayam Ras',
    'daging sapi': 'Daging Sapi Murni',
    'gula': 'Gula Konsumsi',
    'telur ayam': 'Telur Ayam Ras',
    'tepung terigu': 'Tepung Terigu (Curah)',
})
    return merged_data2

In [282]:
def google_trend(folder_path):
    dataframes = []
    for filename in os.listdir(folder_path):
        if filename.endswith('.csv'):
            file_path = os.path.join(folder_path, filename)
            df = pd.read_csv(file_path)
            df['Date'] = pd.to_datetime(df['Date'])
            df['Category'] = filename[:-4]
            df.rename(columns={'Riau Islands': 'Kepulauan Riau', 'Bangka Belitung Islands' : 'Kepulauan Bangka Belitung',
                               'Sumatra Barat' : 'Sumatera Barat', 'Sumatra Utara' : 'Sumatera Utara',
                               'Sumatra Selatan' : 'Sumatera Selatan'}, inplace=True)
            dataframes.append(df)

    if dataframes:
        merged_df = pd.concat(dataframes, ignore_index=True)
        merged_df['Category'] = merged_df['Category'].replace({
    'bawang merah': 'Bawang Merah',
    'bawang putih': 'Bawang Putih Bonggol',
    'cabai merah': 'Cabai Merah Keriting',
    'cabai rawit': 'Cabai Rawit Merah',
    'daging ayam': 'Daging Ayam Ras',
    'daging sapi': 'Daging Sapi Murni',
    'gula': 'Gula Konsumsi',
    'telur ayam': 'Telur Ayam Ras',
    'tepung terigu': 'Tepung Terigu (Curah)',
})
        return merged_df
    else:
        print("No CSV files found in the specified folder.")
        return None

## fillna

In [283]:
def fillna(df):
    missing_percentage = df.isnull().sum() / len(df) * 100
    for column in df.columns:
        if column == 'Price':
                df[column].dropna(inplace=True)
        else:
            df[column] = df[column].fillna(method='ffill')

            
            # # Now apply Exponential Smoothing
            # # Ensure there are enough non-null values to fit the model
            # if df[column].notnull().sum() >= 10:  # Check for at least 10 non-null values
            #     model = ExponentialSmoothing(df[column], trend='add', seasonal='add', seasonal_periods=7, initialization_method='estimated')
            #     model_fit = model.fit()
            #     df[column] = model_fit.fittedvalues
            # else:
            #     # If not enough data, you can choose to fill with mean or drop
            #     mean_value = df[column].mean()
            #     df[column] = df[column].fillna(mean_value)
            # df[column] = df[column].fillna(method='ffill')
            # df[column] = df[column].fillna(0)
            # df[column] = df[column].interpolate(method='akima')
        # else:
        #     df[column] = df[column].fillna(method='ffill')
    return df

## melt

In [284]:
def melt(df, value_name):
    df_reset = df.reset_index()
    melted = df_reset.melt(id_vars=['Date', 'Category'], var_name='Province', value_name=value_name)
    melted.set_index('Date', inplace=True)
    
    return melted

## get_date

In [344]:
def get_date(df, lag, target):
    df['Day'] = df.index.day
    df['day_of_week'] = df.index.dayofweek
    
    for i in range(1, lag + 1):
        df[f'lag_{i}'] = df.groupby('Category')[target].shift(i)
    
    periods = [7, 30, 365]
    for period in periods:
        df[f'sin ({period})'] = np.sin(2 * np.pi * df.index.dayofyear / period)
        df[f'cos ({period})'] = np.cos(2 * np.pi * df.index.dayofyear / period)
    
    df.fillna(method='bfill', inplace=True)

    return df

## load_support

In [286]:
def load_support(path, target):
    df = pd.read_csv(path)
    df.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
    df.set_index('Date', inplace=True)
    df.index = pd.to_datetime(df.index)
    df = df[[target, 'Category']]
    df_pivoted = df.pivot_table(columns='Category', values=target, index = df.index)

    
    return df_pivoted

## train_model

In [339]:
def train_model(df, category):
    model = HistGradientBoostingRegressor(l2_regularization=10.0, learning_rate=0.420324924561727,
                                      max_depth=7, max_iter=1000, min_samples_leaf=20, random_state=42)
    X = df.drop('Price', axis=1)
    y = df['Price']
    model.fit(X, y)
    y_pred = model.predict(X)
    mape = np.mean(np.abs((y - y_pred) / y)) * 100
    print(f"Mean Absolute Percentage Error for {category}: {mape}")
    model_path = fr'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\saved_models\{category}.joblib'
    joblib.dump(model, model_path)
    
    return model

## predict

In [326]:
def predict(model, df, train, category):
    model_path = fr'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\saved_models\{category}.joblib'
    model = joblib.load(model_path)

    df_forecast = df.copy()
    df_forecast['Day'] = df_forecast['Date'].dt.day
    df_forecast['day_of_week'] = df_forecast['Date'].dt.dayofweek
    periods = [7, 30, 365]
    for period in periods:
        df_forecast[f'sin ({period})'] = np.sin(2 * np.pi * df_forecast['Date'].dt.dayofyear / period)
        df_forecast[f'cos ({period})'] = np.cos(2 * np.pi * df_forecast['Date'].dt.dayofyear / period)

    provinces = df_forecast['Province'].unique()
    for province in provinces:
        train_province = train[train['Province'] == province]
        df_province = df_forecast[df_forecast['Province'] == province]
        for j in range(1, 4):
            df_forecast.loc[df_province.index, f'lag_{j}'] = train_province['Price'].iloc[-j] if len(train_province) >= j else None

    predictions = []
    for i in range(len(df_forecast)):
        X_new_row = df_forecast.iloc[i].drop(['Price']).to_frame().T
        y_forecast = model.predict(X_new_row)
        predictions.append(y_forecast[0])
        
        # Update lag features for the NEXT row
        if i < len(df_forecast) - 1:
            province = df_forecast.iloc[i]['Province']
            df_forecast.at[df_forecast.index[i + 1], 'lag_1'] = y_forecast[0]
            for j in range(2, 4):
                df_forecast.at[df_forecast.index[i + 1], f'lag_{j}'] = df_forecast.at[df_forecast.index[i], f'lag_{j-1}']

    df_forecast['Price'] = predictions
    return df_forecast

## pipeline

In [289]:
def pipeline(folder_path, support_df1, support_df2, is_train=True):
    df = load_data(folder_path)
    df = melt(df, 'Price')
    df = df.join(support_df1, how='left', rsuffix='_support')
    df = df.join(support_df2, how='left', rsuffix='_support')
    if is_train:
        df = fillna(df)
    df = get_date(df, 3, 'Price')
    df['Category'] = df['Category'].astype('category')
    df['Province'] = df['Province'].astype('category')
    return df

## Training

In [342]:
folder_path = r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\Harga Bahan Pangan\train'
uang = load_support(r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\forecasted\uang.csv', 'Close')
commodity = load_support(r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\forecasted\commodity.csv', 'Price')
train = pipeline(folder_path, uang, commodity)

C:\Users\farel\AppData\Local\Temp\ipykernel_35424\1357967570.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[column] = df[column].fillna(method='ffill')
C:\Users\farel\AppData\Local\Temp\ipykernel_35424\984510216.py:13: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)

In [343]:
categories = train['Category'].unique()
models = {}
for category in categories:
    train_subset = train[train['Category'] == category]
    model = train_model(train_subset, category)
    models[category] = model

all_predictions = []
y_true = []

for category in categories:
    train_subset = train[train['Category'] == category]
    model = models[category]
    X = train_subset.drop('Price', axis=1)
    y_pred = model.predict(X)
    all_predictions.extend(y_pred)
    y_true.extend(train_subset['Price'])

# Calculate overall MAPE
mape_all = np.mean(np.abs((np.array(y_true) - np.array(all_predictions)) / np.array(y_true))) * 100
print(f"Overall Mean Absolute Percentage Error: {mape_all}")

Mean Absolute Percentage Error for Bawang Merah: 1.444318575255618
Mean Absolute Percentage Error for Bawang Putih Bonggol: 1.1065562285941477
Mean Absolute Percentage Error for Beras Medium: 0.4983758496573927
Mean Absolute Percentage Error for Beras Premium: 0.4359350471486709
Mean Absolute Percentage Error for Cabai Merah Keriting: 2.865042895542453
Mean Absolute Percentage Error for Cabai Rawit Merah: 3.4133971820809523
Mean Absolute Percentage Error for Daging Ayam Ras: 1.0421019283889934
Mean Absolute Percentage Error for Daging Sapi Murni: 0.531343072446003
Mean Absolute Percentage Error for Gula Konsumsi: 0.4092940676220834
Mean Absolute Percentage Error for Minyak Goreng Curah: 0.9704868123641486
Mean Absolute Percentage Error for Minyak Goreng Kemasan Sederhana: 0.9250871542593486
Mean Absolute Percentage Error for Telur Ayam Ras: 0.8865932029332967
Mean Absolute Percentage Error for Tepung Terigu (Curah): 0.7125832074309618
Overall Mean Absolute Percentage Error: 1.1723934787480057

In [13]:
import numpy as np

def mape(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """
    Calculate the Mean Absolute Percentage Error (MAPE).

    Parameters:
    y_true (array-like): True values.
    y_pred (array-like): Predicted values.

    Returns:
    float: The calculated MAPE.
    """
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [203]:
import xgboost as xgb

model = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10, enable_categorical=True)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(mape)

39.576330469577904

In [104]:
mape(y_test, y_pred)

60.451369130362146

In [213]:
from lightgbm import LGBMRegressor

model = LGBMRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
mape

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018133 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4719
[LightGBM] [Info] Number of data points in the train set: 355014, number of used features: 23
[LightGBM] [Info] Start training from score 36198.447667

1.3495363361522763

In [ ]:
#hist gradient boosting
from sklearn.experimental import enable_hist_gradient_boosting


model = HistGradientBoostingRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mape(y_test, y_pred)

5.266117540446549

In [20]:
from skopt import BayesSearchCV
from sklearn.model_selection import KFold  # Change this line

# Define your model
model = LGBMRegressor(random_state=42)

# Define the parameter space for Bayesian optimization
param_space = {
    'n_estimators': (10, 100),
    'max_depth': (1, 10),
    'learning_rate': (0.01, 1.0, 'log-uniform'),
    'num_leaves': (2, 50),
    'min_child_samples': (1, 20),
    'subsample': (0.05, 1.0),
    'colsample_bytree': (0.1, 1.0),
}

# Use KFold for regression tasks
opt = BayesSearchCV(model, param_space, n_iter=32, cv=KFold(n_splits=5), n_jobs=-1, random_state=42)

# Fit the model
opt.fit(X_train, y_train)

# Make predictions
y_pred = opt.predict(X_test)

# Calculate MAPE (Mean Absolute Percentage Error)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f'MAPE: {mape:.2f}%')

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001919 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 559
[LightGBM] [Info] Number of data points in the train set: 338071, number of used features: 4
[LightGBM] [Info] Start training from score 36140.583753
MAPE: 3.53%

In [21]:
best_params = opt.best_params_
print("Best Parameters:", best_params)

# Optionally, create a new model with the best parameters
best_model = LGBMRegressor(**best_params, random_state=42)

# Fit the best model on the training data (if needed)
best_model.fit(X_train, y_train)

# Make predictions with the best model
y_pred_best_model = best_model.predict(X_test)

# Calculate MAPE for the best model
mape_best_model = np.mean(np.abs((y_test - y_pred_best_model) / y_test)) * 100
print(f'MAPE with Best Model: {mape_best_model:.2f}%')

Best Parameters: OrderedDict([('colsample_bytree', 1.0), ('learning_rate', 0.4319256222176345), ('max_depth', 10), ('min_child_samples', 20), ('n_estimators', 70), ('num_leaves', 50), ('subsample', 0.21727297425491027)])
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002052 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 559
[LightGBM] [Info] Number of data points in the train set: 338071, number of used features: 4
[LightGBM] [Info] Start training from score 36140.583753
MAPE with Best Model: 3.53%

In [76]:
from skopt import BayesSearchCV
from sklearn.model_selection import KFold
from sklearn.experimental import enable_hist_gradient_boosting  # noqa
from sklearn.ensemble import HistGradientBoostingRegressor
import numpy as np

model = HistGradientBoostingRegressor(random_state=42)
param_space = {
    'max_iter': (100, 1000),
    'max_depth': (1, 10),
    'learning_rate': (0.01, 1.0, 'log-uniform'),
    'min_samples_leaf': (1, 20),
    'l2_regularization': (0.0, 10.0)
}
opt = BayesSearchCV(model, param_space, n_iter=32, cv=KFold(n_splits=5), n_jobs=-1, random_state=42)
opt.fit(X_train, y_train)

y_pred = opt.predict(X_test)

mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f'MAPE: {mape:.2f}%')

best_params = opt.best_params_
print("Best Parameters:", best_params)

best_model = HistGradientBoostingRegressor(**best_params, random_state=42)

best_model.fit(X_train, y_train)
y_pred_best_model = best_model.predict(X_test)

mape_best_model = np.mean(np.abs((y_test - y_pred_best_model) / y_test)) * 100
print(f'MAPE with Best Model: {mape_best_model:.2f}%')

MAPE: 2.12%
Best Parameters: OrderedDict([('l2_regularization', 10.0), ('learning_rate', 0.420324924561727), ('max_depth', 7), ('max_iter', 1000), ('min_samples_leaf', 20)])
MAPE with Best Model: 2.12%

In [199]:
model = HistGradientBoostingRegressor(l2_regularization=10.0, learning_rate=0.420324924561727,
                                      max_depth=7, max_iter=1000, min_samples_leaf=20, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f'MAPE: {mape:}%')

MAPE: 1.4355036460880168%

In [77]:
y_pred = opt.predict(X_test)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print(f'MAPE: {mape:.2f}%')

MAPE: 2.12%

## Predicting

In [292]:
folder_test = r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\Harga Bahan Pangan\test'
test = pipeline(folder_test, uang, commodity)

C:\Users\farel\AppData\Local\Temp\ipykernel_35424\1357967570.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[column] = df[column].fillna(method='ffill')
C:\Users\farel\AppData\Local\Temp\ipykernel_35424\1706092442.py:13: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)

In [327]:
categories = test['Category'].unique()
results = []

for category in categories:
    train_subset = train[train['Category'] == category]
    test_subset = test[test['Category'] == category]
    
    test_subset = test_subset.reset_index()
    
    y_pred = predict(model, test_subset, train_subset, category)
    
    y_pred = y_pred.reset_index(drop=True)
    
    test_subset.loc[:, 'Price'] = y_pred['Price']
    for j in range(1, 4):
        test_subset.loc[:, f'lag_{j}'] = y_pred[f'lag_{j}']
    
    test_subset = test_subset.set_index('Date')
    
    test_subset['id'] = test_subset['Category'].astype(str) + '/' + test_subset['Province'].astype(str) + '/' + (test_subset.index).astype(str)
    
    results.append(test_subset)

prediction = pd.concat(results)

In [333]:
prediction = prediction[['id', 'Price']]
prediction.reset_index()
prediction

                                                    id         Price
0                         Bawang Merah/Aceh/2024-10-01  28766.835651
1                         Bawang Merah/Aceh/2024-10-02  28819.263565
2                         Bawang Merah/Aceh/2024-10-03  29026.078543
3                         Bawang Merah/Aceh/2024-10-04  29110.919229
4                         Bawang Merah/Aceh/2024-10-05  29154.413155
...                                                ...           ...
40659  Tepung Terigu (Curah)/Sumatera Utara/2024-12-27   9757.011332
40660  Tepung Terigu (Curah)/Sumatera Utara/2024-12-28   9744.824073
40661  Tepung Terigu (Curah)/Sumatera Utara/2024-12-29   9639.927659
40662  Tepung Terigu (Curah)/Sumatera Utara/2024-12-30   9594.478062
40663  Tepung Terigu (Curah)/Sumatera Utara/2024-12-31   9485.529928

[40664 rows x 2 columns]

In [334]:
sample_submission = pd.read_csv(r'C:\Users\farel\OneDrive\Documents\GitHub\Arkavidia-9\Harga Bahan Pangan\sample_submission.csv')

In [335]:
submission = prediction.set_index('id').reindex(sample_submission['id']).reset_index()

In [336]:
submission.to_csv('submission12.csv', index=False)

In [141]:
sample_submission

                                                    id  price
0                         Bawang Merah/Aceh/2024-10-01      0
1                         Bawang Merah/Aceh/2024-10-02      0
2                         Bawang Merah/Aceh/2024-10-03      0
3                         Bawang Merah/Aceh/2024-10-04      0
4                         Bawang Merah/Aceh/2024-10-05      0
...                                                ...    ...
40659  Tepung Terigu (Curah)/Sumatera Utara/2024-12-27      0
40660  Tepung Terigu (Curah)/Sumatera Utara/2024-12-28      0
40661  Tepung Terigu (Curah)/Sumatera Utara/2024-12-29      0
40662  Tepung Terigu (Curah)/Sumatera Utara/2024-12-30      0
40663  Tepung Terigu (Curah)/Sumatera Utara/2024-12-31      0

[40664 rows x 2 columns]